### PR TITLE
docs(all): add code of conduct

### PR DESCRIPTION
**Pull request by clebert**

### CODE REVIEW

**Comment by KingHenne** [comment]
Should we link to this doc in the contributing section, as in 
https://github.com/facebook/react#code-of-conduct?

**Comment by KingHenne** [comment]
Or use the officially recommended text:

> Please note that this project is released with a Contributor Code of Conduct. By participating in this project you agree to abide by its terms.

**Comment by clebert** [comment]
@KingHenne Oh, I read that too late. Should I use the official text?

**Comment by KingHenne** [comment]
Yes, I would prefer that.

**Pull request merged**
